version: "3.8"

services:
    django_u:
        build: .
        container_name: django_u
        command: python manage.py runserver 0.0.0.0:7999
        volumes:
            - .:/usr/src/app
        ports:
            - "7999:7999"
        depends_on:
            - db_u
            - redis
    db_u:
        image: postgres
        container_name: db_u
        env_file:
            - ./crypto/.env
        volumes:
         - data:/var/lib/posgresql/data
    celery_u:
        build: .
        command: celery -A crypto worker -l INFO
        container_name: celery_u
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django_u
            - redis
    redis:
        container_name: redis
        image: "redis:alpine"
    celery-beat_u:
        build: .
        container_name: celery-beat_u
        command: celery -A crypto beat -l info
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django_u
            - redis
            - celery_u
volumes:
  data: