# Generated by Django 3.2.12 on 2022-02-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypto',
            new_name='Asset',
        ),
    ]
