# Generated by Django 3.2.12 on 2022-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_rename_crypto_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('crypto', 'crypto'), ('currency', 'currency'), ('metal', 'metal')], default='crypto', max_length=30),
            preserve_default=False,
        ),
    ]
