# Generated by Django 3.2.12 on 2022-04-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alert_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='daily_diff',
            new_name='convertEUR',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('PLN', 'PLN')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='idA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='convertPLN',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='convertUSD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='guidA',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='currency',
        ),
    ]
