# Generated by Django 3.2.12 on 2022-04-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20220413_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='convertEUR',
            new_name='converterEUR',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='convertPLN',
            new_name='converterPLN',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='convertUSD',
            new_name='converterUSD',
        ),
    ]
