# Generated by Django 3.2.12 on 2022-04-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20220413_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='guidA',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
