# Generated by Django 3.2.12 on 2022-04-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_asset_guida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
    ]
