# Generated by Django 3.2.12 on 2022-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_rename_type_asset_asset_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('currency__in', [('EUR', 'EUR'), ('USD', 'USD'), ('PLN', 'PLN')])), name='crypto_alert_currency'),
        ),
    ]
