# Generated by Django 3.2.12 on 2022-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_auto_20220414_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('asset_type__in', ('crypto', 'currency', 'metal'))), name='crypto_asset_type'),
        ),
    ]
