# Generated by Django 3.2.12 on 2022-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_auto_20220414_2054'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='crypto_alert_currency',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_when_increases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('currency__in', ['USD', 'EUR', 'PLN'])), name='crypto_alert_currency'),
        ),
    ]
